openapi: 3.0.1
info:
  title: Status Update Service
  description: Сервис обновляет статус по переданному ЛС
    кабинета.
  version: 1.0.0
  x-product-version: v1
  x-backend:
    name: SUS
    min-nodes: 1
paths:
  /updatestatus:
    post:
      description: Обновляет статус по ЛС
      operationId: updateStatus
      tags:
        - sus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequest'
      responses:
        200:
          description: Успешно выполнено
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/UpdateResponse'
                  - $ref: '#/components/schemas/ErrorResponse'
        400:
          description: Не удалось найти запись с заданным ЛС, либо переданный MSISDN не совпадает с хранимым
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    UpdateRequest:
      type: object
      properties:
        accountId:
          type: string
        status:
          type: string
        msisdn:
          pattern: '^\d{11,15}$'
          type: string
          description: Номер абонента. В соответствии с E.164, может достигать 15 знаков, содержит только цифры. Включает код страны (CC).
          example: 3809130125566
      required:
        - accountId
        - status
    UpdateResponse:
      type: object
      properties:
        message:
          type: string
    ErrorCode:
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      description: >
        Код ошибки:
        * 1 - Ошибка доступа к БД
        * 2 - Неизвестная ошибка сервиса (неперехваченные исключения)
        * 3 - Не удалось найти запись с заданным ЛС
        * 4 - Переданный мсисдн не соответствует хранимому
        * 5 - Зарезервирован
    ErrorResponse:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
          example: "IllegalStateException: что-то пошло не так"
      required:
        - code
        - message
    OneOfUpdateResponseErrorResponse:
      oneOf:
        - $ref: '#/components/schemas/UpdateResponse'
        - $ref: '#/components/schemas/ErrorResponse'